// CMS Page/Section definitions with field types and default content per tenant

export type FieldType = 'text' | 'textarea' | 'richtext' | 'image' | 'color' | 'number' | 'select' | 'toggle' | 'url';

export interface FieldDefinition {
    key: string;
    label: string;
    type: FieldType;
    placeholder?: string;
    options?: string[]; // for select
    group?: string; // group label for organizing fields
}

export interface SectionDefinition {
    id: string;
    label: string;
    description: string;
    icon: string; // emoji icon
    fields: FieldDefinition[];
    defaults: {
        ireland: Record<string, any>;
        spain: Record<string, any>;
        england: Record<string, any>;
        france: Record<string, any>;
        portugal: Record<string, any>;
    };
    /** Per-tenant section labels */
    labels?: Record<string, string>;
    /** Per-tenant section descriptions */
    descriptions?: Record<string, string>;
}

export interface PageDefinition {
    id: string;
    label: string;
    path: string;
    sections: SectionDefinition[];
    /** Per-tenant page labels */
    labels?: Record<string, string>;
}

/** Get localized section label */
export function getSectionLabel(section: SectionDefinition, tenant: string): string {
    return section.labels?.[tenant] || section.label;
}

/** Get localized section description */
export function getSectionDescription(section: SectionDefinition, tenant: string): string {
    return section.descriptions?.[tenant] || section.description;
}

/** Get localized page label */
export function getPageLabel(page: PageDefinition, tenant: string): string {
    return page.labels?.[tenant] || page.label;
}

export const CMS_PAGES: PageDefinition[] = [
    {
        id: 'home',
        label: 'Home',
        labels: { spain: 'Inicio', france: 'Accueil', portugal: 'Início' },
        path: '/',
        sections: [
            {
                id: 'hero',
                label: 'Hero Section',
                labels: { spain: 'Sección Hero', france: 'Section Hero', portugal: 'Secção Hero' },
                description: 'Main banner at the top of the homepage',
                descriptions: { spain: 'Banner principal en la parte superior de la página de inicio', france: 'Bannière principale en haut de la page d\'accueil', portugal: 'Banner principal no topo da página inicial' },
                icon: '🏠',
                fields: [
                    { key: 'badge_text', label: 'Badge Text', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'heading_highlight', label: 'Highlighted Text', type: 'text', group: 'Content' },
                    { key: 'subheading', label: 'Subheading', type: 'textarea', group: 'Content' },
                    { key: 'cta_line', label: 'CTA Line', type: 'text', group: 'Content' },
                    { key: 'cta_button_text', label: 'Button Text', type: 'text', group: 'Content' },
                    { key: 'cta_button_url', label: 'Button URL', type: 'url', group: 'Content' },
                    { key: 'benefit_1', label: 'Benefit 1', type: 'text', group: 'Benefits Row' },
                    { key: 'benefit_2', label: 'Benefit 2', type: 'text', group: 'Benefits Row' },
                    { key: 'benefit_3', label: 'Benefit 3', type: 'text', group: 'Benefits Row' },
                    { key: 'heading_color', label: 'Heading Color', type: 'color', group: 'Style' },
                    { key: 'highlight_color', label: 'Highlight Color', type: 'color', group: 'Style' },
                    { key: 'bg_color', label: 'Background Color', type: 'color', group: 'Style' },
                    { key: 'heading_font_size', label: 'Heading Font Size', type: 'select', options: ['3xl', '4xl', '5xl', '6xl', '7xl', '8xl'], group: 'Style' },
                ],
                defaults: {
                    ireland: {
                        badge_text: 'Trusted by 1,000+ Irish homeowners',
                        heading: 'BER Cert Ireland – Get Quotes from',
                        heading_highlight: 'Registered Assessors',
                        subheading: 'The fastest, most reliable way to get your official Building Energy Rating. Compare competing quotes from local, SEAI-registered assessors today.',
                        cta_line: 'Get competitive quotes from SEAI-registered local BER Assessors Today',
                        cta_button_text: 'Get a Free Quote',
                        cta_button_url: '/get-quote',
                        benefit_1: '100+ Assessors Nationwide',
                        benefit_2: 'SEAI REGISTERED ASSESSORS ONLY',
                        benefit_3: 'Choose Your Date & Time',
                        heading_color: '#111827',
                        highlight_color: '#007F00',
                        bg_color: '#ffffff',
                        heading_font_size: '7xl',
                    },
                    spain: {
                        badge_text: 'La Mayor Plataforma de Certificados Energéticos',
                        heading: '¿Necesitas un',
                        heading_highlight: 'Certificado Energético?',
                        subheading: 'La forma más rápida y fiable de obtener tu Certificado Energético. Los mejores precios garantizados de más de 1000 certificadores en toda España.',
                        cta_line: 'Obtén los mejores presupuestos de certificadores locales hoy mismo.',
                        cta_button_text: 'Solicitar Presupuesto Gratis',
                        cta_button_url: '/get-quote',
                        benefit_1: '1000+ Certificadores en Toda España',
                        benefit_2: 'SOLO CERTIFICADORES ACREDITADOS',
                        benefit_3: 'Elige tu Fecha y Hora',
                        heading_color: '#111827',
                        highlight_color: '#007F00',
                        bg_color: '#ffffff',
                        heading_font_size: '6xl',
                    },
                    england: {
                        badge_text: "England's Leading EPC Platform",
                        heading: 'Need an',
                        heading_highlight: 'EPC Certificate?',
                        subheading: 'The fastest, most reliable way to get your Energy Performance Certificate. Guaranteed lowest prices from 1000+ accredited assessors across England.',
                        cta_line: 'Get the best quotes from local EPC Assessors today.',
                        cta_button_text: 'Get a Free Quote',
                        cta_button_url: '/get-quote',
                        benefit_1: '1000+ EPC Assessors Across England',
                        benefit_2: 'FULLY ACCREDITED DEAs ONLY',
                        benefit_3: 'Choose Your Date & Time',
                        heading_color: '#111827',
                        highlight_color: '#007F00',
                        bg_color: '#ffffff',
                        heading_font_size: '7xl',
                    },
                    france: {
                        badge_text: "France's Leading DPE Platform",
                        heading: 'Need an',
                        heading_highlight: 'DPE?',
                        subheading: 'The fastest, most reliable way to get your Energy Performance Certificate. Guaranteed lowest prices from 100+ accredited assessors across France.',
                        cta_line: 'Get the best quotes from local DPE Assessors today.',
                        cta_button_text: 'Get a Free Quote',
                        cta_button_url: '/get-quote',
                        benefit_1: '100+ Assessors Across France',
                        benefit_2: 'FULLY ACCREDITED DPEs ONLY',
                        benefit_3: 'Choose Your Date & Time',
                        heading_color: '#111827',
                        highlight_color: '#007F00',
                        bg_color: '#ffffff',
                        heading_font_size: '7xl',
                    },
                    portugal: {
                        badge_text: "Portugal's Leading Energy Cert Platform",
                        heading: 'Need an',
                        heading_highlight: 'Certificado Energético?',
                        subheading: 'The fastest, most reliable way to get your Energy Performance Certificate. Guaranteed lowest prices from 100+ accredited assessors across Portugal.',
                        cta_line: 'Get the best quotes from local Certificado Energético Assessors today.',
                        cta_button_text: 'Get a Free Quote',
                        cta_button_url: '/get-quote',
                        benefit_1: '100+ Assessors Across Portugal',
                        benefit_2: 'FULLY ACCREDITED Peritos ONLY',
                        benefit_3: 'Choose Your Date & Time',
                        heading_color: '#111827',
                        highlight_color: '#007F00',
                        bg_color: '#ffffff',
                        heading_font_size: '7xl',
                    },
                },
            },
            {
                id: 'how_it_works',
                label: 'How It Works',
                labels: { spain: 'Cómo Funciona', france: 'Comment ça Marche', portugal: 'Como Funciona' },
                description: '4-step process section',
                descriptions: { spain: 'Sección de proceso en 4 pasos', france: 'Section processus en 4 étapes', portugal: 'Secção de processo em 4 passos' },
                icon: '⚙️',
                fields: [
                    { key: 'tag', label: 'Section Tag', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'step1_title', label: 'Step 1 Title', type: 'text', group: 'Steps' },
                    { key: 'step1_desc', label: 'Step 1 Description', type: 'textarea', group: 'Steps' },
                    { key: 'step2_title', label: 'Step 2 Title', type: 'text', group: 'Steps' },
                    { key: 'step2_desc', label: 'Step 2 Description', type: 'textarea', group: 'Steps' },
                    { key: 'step3_title', label: 'Step 3 Title', type: 'text', group: 'Steps' },
                    { key: 'step3_desc', label: 'Step 3 Description', type: 'textarea', group: 'Steps' },
                    { key: 'step4_title', label: 'Step 4 Title', type: 'text', group: 'Steps' },
                    { key: 'step4_desc', label: 'Step 4 Description', type: 'textarea', group: 'Steps' },
                    { key: 'bg_color', label: 'Background Color', type: 'color', group: 'Style' },
                ],
                defaults: {
                    ireland: {
                        tag: 'Simple Process', heading: 'How to Get Your BER Certificate',
                        step1_title: 'Select Date', step1_desc: 'Tell us your preferred date & time for assessment.',
                        step2_title: 'Property Details', step2_desc: 'Tell us about your property.',
                        step3_title: 'Receive Quotes', step3_desc: 'Receive competitive prices from local BER assessors.',
                        step4_title: 'Book Assessment', step4_desc: 'Confirm and arrange your assessment.',
                        bg_color: '#f9fafb',
                    },
                    spain: {
                        tag: 'Proceso Sencillo', heading: 'Cómo Funciona',
                        step1_title: 'Elige Fecha', step1_desc: 'Indícanos tu fecha y hora preferida para la visita al inmueble.',
                        step2_title: 'Envía Detalles', step2_desc: 'Comparte la información de tu propiedad en menos de 1 minuto.',
                        step3_title: 'Recibe Presupuestos', step3_desc: 'Recibe precios competitivos de certificadores locales.',
                        step4_title: 'Reserva Online', step4_desc: 'Elige tu presupuesto favorito y confirma al instante.',
                        bg_color: '#f9fafb',
                    },
                    england: {
                        tag: 'Simple Process', heading: 'How It Works',
                        step1_title: 'Select Date', step1_desc: 'Tell us your preferred date & time for the EPC assessment.',
                        step2_title: 'Enter Details', step2_desc: 'Share your property information in less than 1 minute.',
                        step3_title: 'Get Quotes', step3_desc: 'Receive competitive prices from local accredited DEAs.',
                        step4_title: 'Book Online', step4_desc: 'Choose your preferred assessor and confirm instantly.',
                        bg_color: '#f9fafb',
                    },
                    france: {
                        tag: 'Simple Process', heading: 'How It Works',
                        step1_title: 'Select Date', step1_desc: 'Tell us your preferred date & time for the DPE assessment.',
                        step2_title: 'Enter Details', step2_desc: 'Share your property information in less than 1 minute.',
                        step3_title: 'Get Quotes', step3_desc: 'Receive competitive prices from local accredited DPEs.',
                        step4_title: 'Book Online', step4_desc: 'Choose your preferred assessor and confirm instantly.',
                        bg_color: '#f9fafb',
                    },
                    portugal: {
                        tag: 'Simple Process', heading: 'How It Works',
                        step1_title: 'Select Date', step1_desc: 'Tell us your preferred date & time for the Certificado Energético assessment.',
                        step2_title: 'Enter Details', step2_desc: 'Share your property information in less than 1 minute.',
                        step3_title: 'Get Quotes', step3_desc: 'Receive competitive prices from local accredited Peritos.',
                        step4_title: 'Book Online', step4_desc: 'Choose your preferred assessor and confirm instantly.',
                        bg_color: '#f9fafb',
                    },
                },
            },
            {
                id: 'benefits',
                label: 'Why Choose Us',
                labels: { spain: 'Por Qué Elegirnos', france: 'Pourquoi Nous Choisir', portugal: 'Por Que Nos Escolher' },
                description: 'Trust & benefits section with stats',
                descriptions: { spain: 'Sección de confianza y beneficios con estadísticas', france: 'Section confiance et avantages avec statistiques', portugal: 'Secção de confiança e benefícios com estatísticas' },
                icon: '✅',
                fields: [
                    { key: 'tag', label: 'Section Tag', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'heading_highlight', label: 'Highlighted Text', type: 'text', group: 'Content' },
                    { key: 'benefit1_title', label: 'Benefit 1 Title', type: 'text', group: 'Benefits' },
                    { key: 'benefit1_desc', label: 'Benefit 1 Description', type: 'textarea', group: 'Benefits' },
                    { key: 'benefit2_title', label: 'Benefit 2 Title', type: 'text', group: 'Benefits' },
                    { key: 'benefit2_desc', label: 'Benefit 2 Description', type: 'textarea', group: 'Benefits' },
                    { key: 'benefit3_title', label: 'Benefit 3 Title', type: 'text', group: 'Benefits' },
                    { key: 'benefit3_desc', label: 'Benefit 3 Description', type: 'textarea', group: 'Benefits' },
                    { key: 'benefit4_title', label: 'Benefit 4 Title', type: 'text', group: 'Benefits' },
                    { key: 'benefit4_desc', label: 'Benefit 4 Description', type: 'textarea', group: 'Benefits' },
                    { key: 'stat1_value', label: 'Stat 1 Value', type: 'text', group: 'Stats' },
                    { key: 'stat1_label', label: 'Stat 1 Label', type: 'text', group: 'Stats' },
                    { key: 'stat2_value', label: 'Stat 2 Value', type: 'text', group: 'Stats' },
                    { key: 'stat2_label', label: 'Stat 2 Label', type: 'text', group: 'Stats' },
                    { key: 'stat3_value', label: 'Stat 3 Value', type: 'text', group: 'Stats' },
                    { key: 'stat3_label', label: 'Stat 3 Label', type: 'text', group: 'Stats' },
                ],
                defaults: {
                    ireland: {
                        tag: 'The Advantage', heading: 'Why Homeowners Trust', heading_highlight: 'The BER Man',
                        benefit1_title: 'Compare Multiple Quotes', benefit1_desc: 'Receive quotes from trusted assessors and find the option that suits your needs.',
                        benefit2_title: 'SEAI-registered BER Assessors', benefit2_desc: 'Every assessor is verified to help maintain high service standards.',
                        benefit3_title: 'Book with Confidence', benefit3_desc: "We're committed to helping property owners connect with trusted professionals.",
                        benefit4_title: 'Quick Online Booking', benefit4_desc: 'Choose an appointment time that fits your schedule.',
                        stat1_value: '1k+', stat1_label: 'Users Served',
                        stat2_value: '100+', stat2_label: 'Assessors',
                        stat3_value: '4.9/5', stat3_label: 'Average Rating',
                    },
                    spain: {
                        tag: 'La Ventaja', heading: 'Razones para', heading_highlight: 'confiar en nosotros',
                        benefit1_title: 'Visita Presencial Profesional', benefit1_desc: 'No realizamos visitas virtuales, solo hacemos certificaciones tras una visita exhaustiva y profesional. Además nuestros colaboradores les asesoran y les darán los mejores consejos para mejorar la Eficiencia Energética de su propiedad.',
                        benefit2_title: 'Solo Certificadores Acreditados', benefit2_desc: 'Todos los certificadores están plenamente acreditados y verificados.',
                        benefit3_title: 'Garantía de Devolución', benefit3_desc: 'Te aseguramos un servicio profesional o te devolvemos tu dinero.',
                        benefit4_title: 'Reserva Online Instantánea', benefit4_desc: 'Sin llamadas de teléfono de ida y vuelta. Reserva todo en tiempo real.',
                        stat1_value: '1k+', stat1_label: 'Usuarios Atendidos',
                        stat2_value: '1000+', stat2_label: 'Certificadores',
                        stat3_value: '4.9/5', stat3_label: 'Valoración Media',
                    },
                    england: {
                        tag: 'The Advantage', heading: 'Why Homeowners Trust', heading_highlight: 'EPC Cert',
                        benefit1_title: 'Lowest Prices Guaranteed', benefit1_desc: 'Receive multiple quotes and choose the best option for you.',
                        benefit2_title: 'Accredited DEAs Only', benefit2_desc: 'Every Domestic Energy Assessor is fully accredited and vetted.',
                        benefit3_title: 'Money-Back Guarantee', benefit3_desc: 'We ensure you get a professional service or your money back.',
                        benefit4_title: 'Instant Online Booking', benefit4_desc: 'No back-and-forth phone calls. Book everything in real-time.',
                        stat1_value: '1k+', stat1_label: 'Homeowners Served',
                        stat2_value: '100+', stat2_label: 'DEA Assessors',
                        stat3_value: '4.9/5', stat3_label: 'Average Rating',
                    },
                    france: {
                        tag: 'The Advantage', heading: 'Why Homeowners Trust', heading_highlight: 'DPE Cert',
                        benefit1_title: 'Lowest Prices Guaranteed', benefit1_desc: 'Receive multiple quotes and choose the best option for you.',
                        benefit2_title: 'Accredited DPEs Only', benefit2_desc: 'Every Domestic Energy Assessor is fully accredited and vetted.',
                        benefit3_title: 'Money-Back Guarantee', benefit3_desc: 'We ensure you get a professional service or your money back.',
                        benefit4_title: 'Instant Online Booking', benefit4_desc: 'No back-and-forth phone calls. Book everything in real-time.',
                        stat1_value: '1k+', stat1_label: 'Homeowners Served',
                        stat2_value: '100+', stat2_label: 'DPE Assessors',
                        stat3_value: '4.9/5', stat3_label: 'Average Rating',
                    },
                    portugal: {
                        tag: 'The Advantage', heading: 'Why Homeowners Trust', heading_highlight: 'Certificado Energético Cert',
                        benefit1_title: 'Lowest Prices Guaranteed', benefit1_desc: 'Receive multiple quotes and choose the best option for you.',
                        benefit2_title: 'Accredited Peritos Only', benefit2_desc: 'Every Domestic Energy Assessor is fully accredited and vetted.',
                        benefit3_title: 'Money-Back Guarantee', benefit3_desc: 'We ensure you get a professional service or your money back.',
                        benefit4_title: 'Instant Online Booking', benefit4_desc: 'No back-and-forth phone calls. Book everything in real-time.',
                        stat1_value: '1k+', stat1_label: 'Homeowners Served',
                        stat2_value: '100+', stat2_label: 'Perito Assessors',
                        stat3_value: '4.9/5', stat3_label: 'Average Rating',
                    },
                },
            },
            {
                id: 'reviews',
                label: 'Reviews',
                labels: { spain: 'Opiniones', france: 'Avis', portugal: 'Avaliações' },
                description: 'Customer testimonials section',
                descriptions: { spain: 'Sección de testimonios de clientes', france: 'Section témoignages clients', portugal: 'Secção de depoimentos de clientes' },
                icon: '⭐',
                fields: [
                    { key: 'heading', label: 'Rating Label', type: 'text', group: 'Content' },
                    { key: 'subheading', label: 'Subtitle', type: 'text', group: 'Content' },
                    { key: 'review1_author', label: 'Review 1 Author', type: 'text', group: 'Review 1' },
                    { key: 'review1_location', label: 'Review 1 Location', type: 'text', group: 'Review 1' },
                    { key: 'review1_quote', label: 'Review 1 Quote', type: 'textarea', group: 'Review 1' },
                    { key: 'review2_author', label: 'Review 2 Author', type: 'text', group: 'Review 2' },
                    { key: 'review2_location', label: 'Review 2 Location', type: 'text', group: 'Review 2' },
                    { key: 'review2_quote', label: 'Review 2 Quote', type: 'textarea', group: 'Review 2' },
                    { key: 'review3_author', label: 'Review 3 Author', type: 'text', group: 'Review 3' },
                    { key: 'review3_location', label: 'Review 3 Location', type: 'text', group: 'Review 3' },
                    { key: 'review3_quote', label: 'Review 3 Quote', type: 'textarea', group: 'Review 3' },
                ],
                defaults: {
                    ireland: {
                        heading: 'What homeowners say about The Berman', subheading: 'Based on 1,000+ verified customer reviews and ratings',
                        review1_author: 'Michael Byrne', review1_location: 'Dublin', review1_quote: 'Used the platform twice now. Both times I got several quotes within an hour and the assessor was super professional. Saved about €30 vs other sites.',
                        review2_author: "Sarah O'Toole", review2_location: 'Cork', review2_quote: 'Extremely easy to use. I loved that I could see the SEAI registration numbers and reviews for the assessors before booking. Highly recommended for landlords.',
                        review3_author: 'James Murphy', review3_location: 'Galway', review3_quote: 'Fast turnaround and competitive pricing. The portal makes it very simple to manage everything and the certificate was issued within 24 hours of inspection.',
                    },
                    spain: {
                        heading: 'Excelente', subheading: 'Basado en 1.000 valoraciones verificadas de clientes',
                        review1_author: 'Carlos García', review1_location: 'Madrid', review1_quote: 'He usado la plataforma dos veces. En ambas recibí varios presupuestos en menos de una hora y el certificador fue muy profesional. Ahorré unos 30€ respecto a otras webs.',
                        review2_author: 'Lucía Martínez', review2_location: 'Barcelona', review2_quote: 'Extremadamente fácil de usar. Me encantó poder ver la acreditación y las reseñas de los certificadores antes de reservar. Muy recomendable para propietarios.',
                        review3_author: 'Javier Fernández', review3_location: 'Valencia', review3_quote: 'Rapidez y precios competitivos. El portal hace muy sencillo gestionarlo todo y el certificado se emitió en las 24 horas siguientes a la inspección.',
                    },
                    england: {
                        heading: 'Excellent', subheading: 'Based on 1,000 Verified Customer Ratings',
                        review1_author: 'James Thompson', review1_location: 'London', review1_quote: 'Used the platform twice now. Both times I got several quotes within an hour and the assessor was super professional. Saved about £30 vs other sites.',
                        review2_author: 'Sarah Williams', review2_location: 'Manchester', review2_quote: 'Extremely easy to use. I loved that I could verify the DEA accreditation and read reviews before booking. Highly recommended for landlords needing EPCs.',
                        review3_author: 'David Clarke', review3_location: 'Birmingham', review3_quote: 'Fast turnaround and competitive pricing. The portal makes it very simple to manage everything and the EPC was issued within 24 hours of the assessment.',
                    },
                    france: {
                        heading: 'Excellent', subheading: 'Based on 1,000 Verified Customer Ratings',
                        review1_author: 'James Thompson', review1_location: 'Paris', review1_quote: 'Used the platform twice now. Both times I got several quotes within an hour and the assessor was super professional. Saved about €30 vs other sites.',
                        review2_author: 'Sarah Williams', review2_location: 'Manchester', review2_quote: 'Extremely easy to use. I loved that I could verify the DPE accreditation and read reviews before booking. Highly recommended for landlords needing DPEs.',
                        review3_author: 'David Clarke', review3_location: 'Birmingham', review3_quote: 'Fast turnaround and competitive pricing. The portal makes it very simple to manage everything and the DPE was issued within 24 hours of the assessment.',
                    },
                    portugal: {
                        heading: 'Excellent', subheading: 'Based on 1,000 Verified Customer Ratings',
                        review1_author: 'James Thompson', review1_location: 'Lisboa', review1_quote: 'Used the platform twice now. Both times I got several quotes within an hour and the assessor was super professional. Saved about €30 vs other sites.',
                        review2_author: 'Sarah Williams', review2_location: 'Porto', review2_quote: 'Extremely easy to use. I loved that I could verify the ADENE registration and read reviews before booking. Highly recommended for landlords needing energy certificates.',
                        review3_author: 'David Clarke', review3_location: 'Faro', review3_quote: 'Fast turnaround and competitive pricing. The portal makes it very simple to manage everything and the certificate was issued within 24 hours of the assessment.',
                    },
                },
            },
            {
                id: 'assessor_cta',
                label: 'Assessor CTA',
                labels: { spain: 'CTA Certificador', france: 'CTA Évaluateur', portugal: 'CTA Certificador' },
                description: 'Call to action for assessors to join',
                descriptions: { spain: 'Llamada a la acción para que certificadores se unan', france: 'Appel à l\'action pour les évaluateurs', portugal: 'Chamada à ação para certificadores se juntarem' },
                icon: '📣',
                fields: [
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'description', label: 'Description', type: 'textarea', group: 'Content' },
                    { key: 'cta_text', label: 'Button Text', type: 'text', group: 'Content' },
                    { key: 'cta_url', label: 'Button URL', type: 'url', group: 'Content' },
                ],
                defaults: {
                    ireland: { heading: 'Are You a BER Assessor?', description: 'SEAI-registered assessors can join our nationwide network and connect with property owners looking for BER assessments in their area.', cta_text: 'Register as an Assessor', cta_url: '/signup?role=contractor' },
                    spain: { heading: '¿Eres Certificador Energético?', description: 'Regístrate y recibe leads de trabajo locales, directamente en tu teléfono.', cta_text: 'Únete Ahora', cta_url: '/signup?role=contractor' },
                    england: { heading: 'Are You a Domestic Energy Assessor?', description: 'Register with epccert.com and receive local EPC job leads, straight to your phone.', cta_text: 'Join Now', cta_url: '/signup?role=contractor' },
                    france: { heading: 'Êtes-vous Diagnostiqueur DPE?', description: 'Inscrivez-vous sur dpefrance.eu et recevez des leads locaux.', cta_text: 'Rejoindre', cta_url: '/signup?role=contractor' },
                    portugal: { heading: 'É Perito Certificado?', description: 'Registe-se em certificadopt.eu e receba leads locais.', cta_text: 'Juntar-se', cta_url: '/signup?role=contractor' },
                },
            },
            {
                id: 'catalogue_promo',
                label: 'Energy Catalogue',
                labels: { spain: 'Catálogo de Energía', france: 'Catalogue Énergie', portugal: 'Catálogo de Energia' },
                description: 'Home energy partners catalogue section',
                descriptions: { spain: 'Sección de catálogo de socios de energía doméstica', france: 'Section catalogue des partenaires énergie', portugal: 'Secção de catálogo de parceiros de energia doméstica' },
                icon: '🔍',
                fields: [
                    { key: 'tag', label: 'Section Tag', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'heading_highlight', label: 'Highlighted Text', type: 'text', group: 'Content' },
                    { key: 'description', label: 'Description', type: 'textarea', group: 'Content' },
                    { key: 'cta1_text', label: 'CTA 1 Text', type: 'text', group: 'Buttons' },
                    { key: 'cta2_text', label: 'CTA 2 Text', type: 'text', group: 'Buttons' },
                    { key: 'cta3_text', label: 'CTA 3 Text', type: 'text', group: 'Buttons' },
                    { key: 'image_url', label: 'Section Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: {
                        tag: 'Explore Our Network', heading: 'Home Energy Upgrade Services Across Ireland', heading_highlight: '',
                        description: "Access our curated catalogue of certified home energy businesses. From solar panel installers to insulation specialists, find the right partner for your home's journey to efficiency.",
                        cta1_text: 'Browse Catalogue', cta2_text: 'Register your Business', cta3_text: 'Speak to Advisor',
                        image_url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=800&fm=webp',
                    },
                    spain: {
                        tag: 'Explora Nuestra Red', heading: 'Encuentra los Mejores', heading_highlight: 'Colaboradores de Eficiencia Energética.',
                        description: 'Accede a nuestro catálogo seleccionado de empresas certificadas de eficiencia energética. Desde instaladores de paneles solares hasta especialistas en aislamiento, encuentra el colaborador adecuado para el camino de tu hogar hacia la eficiencia.',
                        cta1_text: 'Explorar Catálogo', cta2_text: 'Registra tu Negocio', cta3_text: 'Habla con un Asesor',
                        image_url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=800&fm=webp',
                    },
                    england: {
                        tag: 'Explore Our Network', heading: 'Find the Best', heading_highlight: 'Home Energy Partners.',
                        description: "Access our curated catalogue of certified home energy businesses. From solar panel installers to insulation specialists, find the right partner for your home's journey to efficiency.",
                        cta1_text: 'Browse Catalogue', cta2_text: 'Register your Business', cta3_text: 'Speak to Advisor',
                        image_url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=800&fm=webp',
                    },
                    france: {
                        tag: 'Explore Our Network', heading: 'Find the Best', heading_highlight: 'Home Energy Partners.',
                        description: "Access our curated catalogue of certified home energy businesses. From solar panel installers to insulation specialists, find the right partner for your home's journey to efficiency.",
                        cta1_text: 'Browse Catalogue', cta2_text: 'Register your Business', cta3_text: 'Speak to Advisor',
                        image_url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=800&fm=webp',
                    },
                    portugal: {
                        tag: 'Explore Our Network', heading: 'Find the Best', heading_highlight: 'Home Energy Partners.',
                        description: "Access our curated catalogue of certified home energy businesses. From solar panel installers to insulation specialists, find the right partner for your home's journey to efficiency.",
                        cta1_text: 'Browse Catalogue', cta2_text: 'Register your Business', cta3_text: 'Speak to Advisor',
                        image_url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?q=80&w=800&fm=webp',
                    },
                },
            },
            {
                id: 'faq',
                label: 'FAQ Section',
                labels: { spain: 'Sección FAQ', france: 'Section FAQ', portugal: 'Secção FAQ' },
                description: 'Frequently asked questions',
                descriptions: { spain: 'Preguntas frecuentes', france: 'Questions fréquemment posées', portugal: 'Perguntas frequentes' },
                icon: '❓',
                fields: [
                    { key: 'tag', label: 'Section Tag', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'faq1_q', label: 'FAQ 1 Question', type: 'text', group: 'FAQ 1' },
                    { key: 'faq1_a', label: 'FAQ 1 Answer', type: 'textarea', group: 'FAQ 1' },
                    { key: 'faq2_q', label: 'FAQ 2 Question', type: 'text', group: 'FAQ 2' },
                    { key: 'faq2_a', label: 'FAQ 2 Answer', type: 'textarea', group: 'FAQ 2' },
                    { key: 'faq3_q', label: 'FAQ 3 Question', type: 'text', group: 'FAQ 3' },
                    { key: 'faq3_a', label: 'FAQ 3 Answer', type: 'textarea', group: 'FAQ 3' },
                    { key: 'faq4_q', label: 'FAQ 4 Question', type: 'text', group: 'FAQ 4' },
                    { key: 'faq4_a', label: 'FAQ 4 Answer', type: 'textarea', group: 'FAQ 4' },
                    { key: 'cta_heading', label: 'CTA Heading', type: 'text', group: 'CTA Box' },
                    { key: 'cta_description', label: 'CTA Description', type: 'textarea', group: 'CTA Box' },
                    { key: 'cta_button', label: 'CTA Button Text', type: 'text', group: 'CTA Box' },
                ],
                defaults: {
                    ireland: {
                        tag: 'Knowledge Base', heading: 'Frequently Asked Questions',
                        faq1_q: 'What Is a BER Certificate?', faq1_a: 'A BER Certificate shows the energy efficiency of a property using a rating from A to G.',
                        faq2_q: 'When Do I Need a BER Certificate?', faq2_a: 'A BER Certificate is usually required when selling or renting a property in Ireland.',
                        faq3_q: 'How Much Does a BER Assessment Cost?', faq3_a: 'The cost depends on the size, type, and location of the property.',
                        faq4_q: 'How Long Is a BER Certificate Valid?', faq4_a: 'Most BER Certificates remain valid for up to 10 years.',
                        cta_heading: 'Ready to Get Your BER Certificate?', cta_description: 'Compare quotes from qualified assessors and arrange your assessment online.',
                        cta_button: 'Get a Quote Online',
                    },
                    spain: {
                        tag: 'Base de Conocimiento', heading: 'Preguntas Frecuentes',
                        faq1_q: '¿Qué es un Certificado Energético?', faq1_a: 'El Certificado de Eficiencia Energética indica el nivel de eficiencia energética de tu propiedad, calificada de la A (más eficiente) a la G (menos eficiente).',
                        faq2_q: '¿Por qué necesito un Certificado Energético?', faq2_a: 'Es obligatorio por ley para vender o alquilar una propiedad. También es necesario para acceder a subvenciones de rehabilitación energética.',
                        faq3_q: '¿Cuánto cuesta?', faq3_a: 'Cada presupuesto es personalizado acorde a las necesidades de nuestros clientes y el tipo de propiedad.',
                        faq4_q: '¿Cuánto tiempo es válido?', faq4_a: 'Un Certificado Energético tiene una validez de hasta 10 años, salvo que se realicen cambios importantes que alteren el rendimiento energético de la propiedad.',
                        cta_heading: '¿Listo para tu Certificado Energético?', cta_description: 'Únete a más de 10000 clientes satisfechos. Obtén presupuestos competitivos de certificadores locales de confianza en segundos.',
                        cta_button: 'Pide Presupuesto Online',
                    },
                    england: {
                        tag: 'Knowledge Base', heading: 'Frequently Asked Questions',
                        faq1_q: 'What is an EPC?', faq1_a: 'An Energy Performance Certificate (EPC) tells you how energy efficient your property is, rated from A (most efficient) to G (least efficient). It also shows potential improvements.',
                        faq2_q: 'Why do I need an EPC?', faq2_a: "It's a legal requirement to have a valid EPC when selling, letting, or building a property in England and Wales. Fines of up to £5,000 apply for non-compliance.",
                        faq3_q: 'How much does it cost?', faq3_a: 'EPC costs typically range from £35 to £120 depending on property size. Our platform ensures you get the most competitive quotes from local accredited DEAs.',
                        faq4_q: 'How long is it valid for?', faq4_a: 'An EPC is valid for 10 years from the date of issue, unless a new one is produced for the property.',
                        cta_heading: 'Ready to get your EPC?', cta_description: 'Join over 1,000 satisfied homeowners. Get competitive quotes from trusted local assessors in seconds.',
                        cta_button: 'Get a Quote Online',
                    },
                    france: {
                        tag: 'Knowledge Base', heading: 'Frequently Asked Questions',
                        faq1_q: 'What is an DPE?', faq1_a: 'An Energy Performance Certificate (DPE) tells you how energy efficient your property is, rated from A (most efficient) to G (least efficient). It also shows potential improvements.',
                        faq2_q: 'Why do I need an DPE?', faq2_a: "It's a legal requirement to have a valid DPE when selling, letting, or building a property in France and Wales. Fines of up to €5,000 apply for non-compliance.",
                        faq3_q: 'How much does it cost?', faq3_a: 'DPE costs typically range from €35 to €120 depending on property size. Our platform ensures you get the most competitive quotes from local accredited DPEs.',
                        faq4_q: 'How long is it valid for?', faq4_a: 'An DPE is valid for 10 years from the date of issue, unless a new one is produced for the property.',
                        cta_heading: 'Ready to get your DPE?', cta_description: 'Join over 1,000 satisfied homeowners. Get competitive quotes from trusted local assessors in seconds.',
                        cta_button: 'Get a Quote Online',
                    },
                    portugal: {
                        tag: 'Knowledge Base', heading: 'Frequently Asked Questions',
                        faq1_q: 'What is an Certificado Energético?', faq1_a: 'An Energy Performance Certificate (Certificado Energético) tells you how energy efficient your property is, rated from A (most efficient) to G (least efficient). It also shows potential improvements.',
                        faq2_q: 'Why do I need an Certificado Energético?', faq2_a: "It's a legal requirement to have a valid Certificado Energético when selling, letting, or building a property in Portugal and Wales. Fines of up to £5,000 apply for non-compliance.",
                        faq3_q: 'How much does it cost?', faq3_a: 'Certificado Energético costs typically range from £35 to £120 depending on property size. Our platform ensures you get the most competitive quotes from local accredited Peritos.',
                        faq4_q: 'How long is it valid for?', faq4_a: 'An Certificado Energético is valid for 10 years from the date of issue, unless a new one is produced for the property.',
                        cta_heading: 'Ready to get your Certificado Energético?', cta_description: 'Join over 1,000 satisfied homeowners. Get competitive quotes from trusted local assessors in seconds.',
                        cta_button: 'Get a Quote Online',
                    },
                },
            },
            {
                id: 'newsletter',
                label: 'Newsletter',
                labels: { spain: 'Boletín', france: 'Newsletter', portugal: 'Newsletter' },
                description: 'Email subscription section',
                descriptions: { spain: 'Sección de suscripción por correo electrónico', france: 'Section d\'abonnement email', portugal: 'Secção de subscrição por email' },
                icon: '📧',
                fields: [
                    { key: 'tag', label: 'Section Tag', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'description', label: 'Description', type: 'textarea', group: 'Content' },
                    { key: 'button_text', label: 'Button Text', type: 'text', group: 'Content' },
                    { key: 'placeholder', label: 'Email Placeholder', type: 'text', group: 'Content' },
                ],
                defaults: {
                    ireland: {
                        tag: 'Premium Resources', heading: 'Get Our Complete Home Energy Upgrade Guide',
                        description: 'Join 5,000+ homeowners receiving our weekly energy updates, flash sales, and exclusive energy upgrade offers.',
                        button_text: 'Subscribe to news', placeholder: 'Enter your email address',
                    },
                    spain: {
                        tag: 'Recursos Premium', heading: 'Consigue nuestra guía completa de mejoras energéticas',
                        description: 'Únete a más de 5.000 propietarios que reciben nuestras novedades energéticas semanales, ofertas flash y promociones exclusivas de rehabilitación energética.',
                        button_text: 'Suscribirse', placeholder: 'Introduce tu correo electrónico',
                    },
                    england: {
                        tag: 'Premium Resources', heading: 'Get Our Complete Home Energy Upgrade Guide',
                        description: 'Join 5,000+ homeowners receiving our weekly energy updates, EPC tips, and exclusive home improvement offers.',
                        button_text: 'Subscribe to news', placeholder: 'Enter your email address',
                    },
                    france: {
                        tag: 'Premium Resources', heading: 'Get Our Complete Home Energy Upgrade Guide',
                        description: 'Join 5,000+ homeowners receiving our weekly energy updates, DPE tips, and exclusive home improvement offers.',
                        button_text: 'Subscribe to news', placeholder: 'Enter your email address',
                    },
                    portugal: {
                        tag: 'Premium Resources', heading: 'Get Our Complete Home Energy Upgrade Guide',
                        description: 'Join 5,000+ homeowners receiving our weekly energy updates, Certificado Energético tips, and exclusive home improvement offers.',
                        button_text: 'Subscribe to news', placeholder: 'Enter your email address',
                    },
                },
            },
        ],
    },
    {
        id: 'about',
        label: 'About',
        labels: { spain: 'Nosotros', france: 'À Propos', portugal: 'Sobre' },
        path: '/about',
        sections: [
            {
                id: 'hero',
                label: 'Hero Section',
                labels: { spain: 'Sección Hero', france: 'Section Hero', portugal: 'Secção Hero' },
                description: 'About page header',
                descriptions: { spain: 'Encabezado de la página Sobre Nosotros', france: 'En-tête de la page À Propos', portugal: 'Cabeçalho da página Sobre' },
                icon: '🏢',
                fields: [
                    { key: 'tag', label: 'Section Tag', type: 'text', group: 'Content' },
                    { key: 'heading_line1', label: 'Heading Line 1', type: 'text', group: 'Content' },
                    { key: 'heading_line2', label: 'Heading Line 2', type: 'text', group: 'Content' },
                    { key: 'description', label: 'Description', type: 'textarea', group: 'Content' },
                ],
                defaults: {
                    ireland: { tag: 'Who We Are', heading_line1: 'About The BER', heading_line2: 'Man', description: "The BER Man helps property owners connect with qualified BER assessors through a simple and transparent process. Our platform makes arranging BER assessments easier while helping users make informed energy decisions." },
                    spain: { tag: 'Nuestra Misión', heading_line1: 'Precisión en cada', heading_line2: 'Certificación.', description: 'le ayudamos a entender, mejorar y ahorrar dinero con una certificación de eficiencia energética que le será explicada por los mejores profesionales del sector.' },
                    england: { tag: 'Who We Are', heading_line1: 'Helping Property Owners', heading_line2: 'Arrange EPC Assessments Across England', description: 'Expand to homeowners, landlords and businesses' },
                    france: { tag: 'Our Mission', heading_line1: 'Precision in every', heading_line2: 'Assessment.', description: "Helping homeowners across France understand, improve, and certify their property's energy performance." },
                    portugal: { tag: 'Our Mission', heading_line1: 'Precision in every', heading_line2: 'Assessment.', description: "Helping homeowners across Portugal understand, improve, and certify their property's energy performance." },
                },
            },
            {
                id: 'story',
                label: 'Our Story',
                labels: { spain: 'Nuestra Historia', france: 'Notre Histoire', portugal: 'A Nossa História' },
                description: 'Company history and story',
                descriptions: { spain: 'Historia y trayectoria de la empresa', france: 'Histoire et parcours de l\'entreprise', portugal: 'História e trajetória da empresa' },
                icon: '📖',
                fields: [
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'paragraph1', label: 'Paragraph 1', type: 'textarea', group: 'Content' },
                    { key: 'paragraph2', label: 'Paragraph 2', type: 'textarea', group: 'Content' },
                    { key: 'paragraph3', label: 'Paragraph 3', type: 'textarea', group: 'Content' },
                    { key: 'paragraph4', label: 'Paragraph 4', type: 'textarea', group: 'Content' },
                    { key: 'stat1_value', label: 'Stat 1 Value', type: 'text', group: 'Stats' },
                    { key: 'stat1_label', label: 'Stat 1 Label', type: 'text', group: 'Stats' },
                    { key: 'stat2_value', label: 'Stat 2 Value', type: 'text', group: 'Stats' },
                    { key: 'stat2_label', label: 'Stat 2 Label', type: 'text', group: 'Stats' },
                    { key: 'stat3_value', label: 'Stat 3 Value', type: 'text', group: 'Stats' },
                    { key: 'stat3_label', label: 'Stat 3 Label', type: 'text', group: 'Stats' },
                ],
                defaults: {
                    ireland: {
                        heading: 'Connecting Property Owners with Qualified BER Assessors',
                        paragraph1: "The BER Man was created to make arranging BER assessments simpler, more transparent, and easier to manage for property owners.",
                        paragraph2: "What started as a specialist service has grown into a trusted network of SEAI-registered BER Assessors, helping homeowners, landlords, estate agents, and businesses access professional energy rating services through one convenient platform.",
                        paragraph3: "Today, the BER Man helps connect property owners with qualified assessors while making BER assessments easier to arrange and understand.",
                        paragraph4: "Our focus remains simple: helping people make informed decisions about their property's energy performance with confidence.",
                        stat1_value: '1,000+', stat1_label: 'BER Assessments Completed',
                        stat2_value: '100+', stat2_label: 'Qualified Assessors',
                        stat3_value: 'SEAI', stat3_label: 'Registered BER Assessors',
                    },
                    spain: {
                        heading: 'Nuestra Historia',
                        paragraph1: 'Certificado Energético se fundó con un objetivo claro: aportar claridad profesional y rigor técnico al sector de la certificación energética en España.',
                        paragraph2: 'Lo que comenzó como un equipo especializado en Madrid se ha convertido en una red nacional de certificadores acreditados.',
                        paragraph3: 'Hoy, Certificado Energético es una referencia en consultoría energética en España. Hemos realizado con éxito más de 10.000 certificaciones.',
                        paragraph4: 'Mirando al futuro, nos centramos en la innovación y la excelencia.',
                        stat1_value: '10k+', stat1_label: 'Certificaciones Energéticas Emitidas',
                        stat2_value: '100+', stat2_label: 'Red Nacional de Certificadores',
                        stat3_value: 'CEE', stat3_label: 'Certificadores Acreditados',
                    },
                    england: {
                        heading: 'Our Story',
                        paragraph1: "EPC Cert was established to make Energy Performance Certificate (EPC) assessments easier for property owners, landlords, estate agents and businesses across England.\n\nWe understand that obtaining an EPC is often a necessary part of selling, renting or managing a property, yet finding a qualified assessor and arranging an appointment can be time-consuming. Our platform was created to simplify the process by connecting customers with accredited EPC assessors through a trusted nationwide network.",
                        paragraph2: "From residential homes and rental properties to commercial buildings, EPC Cert helps customers access professional EPC assessment services with greater convenience and confidence. We focus on providing a straightforward booking experience, flexible appointment availability and access to qualified assessors who operate in accordance with current EPC regulations and industry standards.",
                        paragraph3: "As energy efficiency continues to play an important role in the property sector, our commitment remains the same: helping customers across England access reliable EPC assessment services while making the process clear, efficient and stress-free.",
                        paragraph4: "",
                        stat1_value: '1k+', stat1_label: 'Completed EPC Assessments',
                        stat2_value: '100+', stat2_label: 'Accredited EPC Assessors Across England',
                        stat3_value: 'Level 3', stat3_label: 'Qualified Energy Assessors',
                    },
                    france: {
                        heading: 'Our Story',
                        paragraph1: "DPE Cert was founded with a singular objective: to bring professional clarity and technical rigor to France's energy performance certificate industry.",
                        paragraph2: "What began as a small team in Paris has grown into a nationwide network of accredited Domestic Energy Assessors.",
                        paragraph3: "Today, DPE Cert stands as a trusted platform for energy assessments across France. We have successfully facilitated thousands of DPEs.",
                        paragraph4: "As we look toward the future, our focus continues to be on innovation, compliance, and helping homeowners meet the latest DPE regulations.",
                        stat1_value: '1k+', stat1_label: 'Completed DPE Assessments',
                        stat2_value: '100+', stat2_label: 'Accredited DPEs Nationwide',
                        stat3_value: 'Level 3', stat3_label: 'Qualified Energy Assessors',
                    },
                    portugal: {
                        heading: 'Our Story',
                        paragraph1: "Certificado Energético Cert was founded with a singular objective: to bring professional clarity and technical rigor to Portugal's energy performance certificate industry.",
                        paragraph2: "What began as a small team in Lisboa has grown into a nationwide network of accredited Domestic Energy Assessors.",
                        paragraph3: "Today, Certificado Energético Cert stands as a trusted platform for energy assessments across Portugal. We have successfully facilitated thousands of Certificado Energéticos.",
                        paragraph4: "As we look toward the future, our focus continues to be on innovation, compliance, and helping homeowners meet the latest Certificado Energético regulations.",
                        stat1_value: '1k+', stat1_label: 'Completed Certificado Energético Assessments',
                        stat2_value: '100+', stat2_label: 'Accredited Peritos Nationwide',
                        stat3_value: 'Level 3', stat3_label: 'Qualified Energy Assessors',
                    },
                },
            },
            {
                id: 'cta',
                label: 'Join CTA',
                labels: { spain: 'CTA Unirse', france: 'CTA Rejoindre', portugal: 'CTA Juntar-se' },
                description: 'Bottom call-to-action',
                descriptions: { spain: 'Llamada a la acción al final de la página', france: 'Appel à l\'action en bas de page', portugal: 'Chamada à ação no final da página' },
                icon: '🚀',
                fields: [
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'heading_highlight', label: 'Brand Name', type: 'text', group: 'Content' },
                    { key: 'description', label: 'Description', type: 'textarea', group: 'Content' },
                    { key: 'button_text', label: 'Button Text', type: 'text', group: 'Content' },
                ],
                defaults: {
                    ireland: { heading: 'Ready to Arrange Your', heading_highlight: 'BER Assessment?', description: 'Connect with qualified BER assessors and compare options for your property through one simple platform.', button_text: 'Get My BER Quote' },
                    spain: { heading: 'Únete a la familia', heading_highlight: 'Certificado Energético', description: '¿Preparado para tu certificación energética profesional? Nuestro equipo nacional está listo para ayudarte hoy mismo.', button_text: 'Pedir mi Presupuesto' },
                    england: { heading: 'Need an EPC Certificate?', heading_highlight: '', description: 'Compare quotes from accredited EPC assessors serving homeowners, landlords and businesses across England.', button_text: 'Get a Free Quote' },
                    france: { heading: 'Join', heading_highlight: 'DPE Cert', description: 'Ready for a professional DPE assessment? Our nationwide network of accredited DPEs is ready to help you today.', button_text: 'Get My DPE Quote' },
                    portugal: { heading: 'Join', heading_highlight: 'Certificado Energético Cert', description: 'Ready for a professional Certificado Energético assessment? Our nationwide network of accredited Peritos is ready to help you today.', button_text: 'Get My Certificado Energético Quote' },
                },
            },
        ],
    },
    {
        id: 'contact',
        label: 'Contact',
        labels: { spain: 'Contacto', france: 'Contact', portugal: 'Contacto' },
        path: '/contact-us',
        sections: [
            {
                id: 'hero',
                label: 'Contact Header',
                labels: { spain: 'Encabezado de Contacto', france: 'En-tête Contact', portugal: 'Cabeçalho de Contacto' },
                description: 'Contact page heading and intro',
                descriptions: { spain: 'Encabezado e introducción de la página de contacto', france: 'En-tête et introduction de la page de contact', portugal: 'Cabeçalho e introdução da página de contacto' },
                icon: '📞',
                fields: [
                    { key: 'badge', label: 'Badge Text', type: 'text', group: 'Content' },
                    { key: 'heading_line1', label: 'Heading Line 1', type: 'text', group: 'Content' },
                    { key: 'heading_line2', label: 'Heading Line 2', type: 'text', group: 'Content' },
                    { key: 'subtitle', label: 'Subtitle', type: 'textarea', group: 'Content' },
                ],
                defaults: {
                    ireland: { badge: 'Get In Touch', heading_line1: 'Book a BER', heading_line2: 'Assessment in Ireland', subtitle: 'Contact The BER Man to book a BER assessment, connect with qualified BER assessors, or get support with your enquiry.' },
                    spain: { badge: 'Ponte en Contacto', heading_line1: '¿En qué podemos', heading_line2: 'ayudarte?', subtitle: '¿Tienes alguna pregunta sobre certificaciones energéticas? Nuestro equipo está aquí para ayudarte.' },
                    england: { badge: 'Get In Touch', heading_line1: 'Book an EPC Assessment', heading_line2: 'in England', subtitle: 'Compare quotes from accredited EPC assessors across England and arrange your EPC assessment with confidence.' },
                    france: { badge: 'Get In Touch', heading_line1: 'How can we', heading_line2: 'help?', subtitle: 'Have a question about DPE assessments? Our team is here to provide the support you need.' },
                    portugal: { badge: 'Get In Touch', heading_line1: 'How can we', heading_line2: 'help?', subtitle: 'Have a question about Certificado Energético assessments? Our team is here to provide the support you need.' },
                },
            },
            {
                id: 'contact_details',
                label: 'Contact Details',
                labels: { spain: 'Detalles de Contacto', france: 'Coordonnées', portugal: 'Detalhes de Contacto' },
                description: 'Phone, address, and business hours shown on the contact page',
                descriptions: { spain: 'Teléfono, dirección y horario mostrados en la página de contacto', france: 'Téléphone, adresse et horaires affichés sur la page de contact', portugal: 'Telefone, morada e horário mostrados na página de contacto' },
                icon: '📋',
                fields: [
                    { key: 'phone', label: 'Phone Number', type: 'text', group: 'Details' },
                    { key: 'email', label: 'Email Address', type: 'text', group: 'Details' },
                    { key: 'address', label: 'Address', type: 'textarea', group: 'Details' },
                    { key: 'business_hours', label: 'Business Hours', type: 'text', group: 'Details' },
                    { key: 'map_url', label: 'Google Maps URL', type: 'url', group: 'Details' },
                ],
                defaults: {
                    ireland: { phone: '', email: 'hello@theberman.eu', address: '', business_hours: '', map_url: '' },
                    spain: { phone: '', email: 'info@certificadoenergético.eu', address: '', business_hours: '', map_url: '' },
                    england: { phone: '', email: 'hello@epccert.com', address: '', business_hours: '', map_url: '' },
                    france: { phone: '', email: 'contact@dpefrance.eu', address: '', business_hours: '', map_url: '' },
                    portugal: { phone: '', email: 'contact@certificadopt.eu', address: '', business_hours: '', map_url: '' },
                },
            },
        ],
    },
    {
        id: 'location',
        label: 'Location',
        labels: { spain: 'Ubicación', france: 'Localisation', portugal: 'Localização' },
        path: '/dublin',
        sections: [
            {
                id: 'hero',
                label: 'Hero Section',
                labels: { spain: 'Sección Hero', france: 'Section Hero', portugal: 'Secção Hero' },
                description: 'Location page hero content',
                descriptions: { spain: 'Contenido hero de la página de ubicación', france: 'Contenu hero de la page de localisation', portugal: 'Conteúdo hero da página de localização' },
                icon: '📍',
                fields: [
                    { key: 'hero_title', label: 'Hero Title', type: 'text', group: 'Content' },
                    { key: 'hero_subtitle', label: 'Hero Subtitle', type: 'text', group: 'Content' },
                ],
                defaults: {
                    ireland: { hero_title: 'BER Assessors in Dublin', hero_subtitle: 'Find certified assessors in Dublin. Compare quotes and book online.' },
                    spain: { hero_title: 'Técnicos Certificados en Madrid', hero_subtitle: 'Encuentra técnicos certificados en Madrid. Compara presupuestos y reserva online.' },
                    england: { hero_title: 'EPC Assessors in London', hero_subtitle: 'Find certified assessors in London. Compare quotes and book online.' },
                    france: { hero_title: 'Diagnostiqueurs DPE à Paris', hero_subtitle: 'Trouvez des diagnostiqueurs certifiés à Paris. Comparez les devis et réservez en ligne.' },
                    portugal: { hero_title: 'Peritos Certificados em Lisboa', hero_subtitle: 'Encontre peritos certificados em Lisboa. Compare orçamentos e reserve online.' },
                },
            },
            {
                id: 'content',
                label: 'Page Content',
                labels: { spain: 'Contenido de Página', france: 'Contenu de Page', portugal: 'Conteúdo da Página' },
                description: 'Main body text for the location page',
                descriptions: { spain: 'Texto principal de la página de ubicación', france: 'Texte principal de la page de localisation', portugal: 'Texto principal da página de localização' },
                icon: '📝',
                fields: [
                    { key: 'intro_text', label: 'Intro Text', type: 'textarea', group: 'Content' },
                ],
                defaults: {
                    ireland: { intro_text: 'The Berman connects homeowners with BER assessors in Dublin. Our expert assessors are ready to provide high-quality Building Energy Ratings.' },
                    spain: { intro_text: 'Certificado Energético conecta propietarios con técnicos certificados en Madrid. Nuestros técnicos expertos están listos para proporcionar certificados de eficiencia energética de alta calidad.' },
                    england: { intro_text: 'EPC Cert connects homeowners with certified assessors in London. Our expert assessors are ready to provide high-quality Energy Performance Certificates.' },
                    france: { intro_text: 'DPE France connecte les propriétaires avec des diagnostiqueurs certifiés à Paris. Nos experts sont prêts à fournir des diagnostics de performance énergétique de haute qualité.' },
                    portugal: { intro_text: 'Certificado Energético conecta proprietários com peritos certificados em Lisboa. Os nossos peritos estão prontos a fornecer certificados de eficiência energética de alta qualidade.' },
                },
            },
            {
                id: 'seo',
                label: 'SEO Settings',
                labels: { spain: 'Configuración SEO', france: 'Paramètres SEO', portugal: 'Configurações SEO' },
                description: 'Meta tags for search engines',
                descriptions: { spain: 'Meta etiquetas para motores de búsqueda', france: 'Méta-tags pour les moteurs de recherche', portugal: 'Meta tags para motores de busca' },
                icon: '🔍',
                fields: [
                    { key: 'seo_title', label: 'SEO Title', type: 'text', group: 'SEO' },
                    { key: 'seo_description', label: 'SEO Description', type: 'textarea', group: 'SEO' },
                    { key: 'meta_keywords', label: 'Meta Keywords', type: 'text', group: 'SEO' },
                    { key: 'is_active', label: 'Page Active', type: 'toggle', group: 'SEO' },
                ],
                defaults: {
                    ireland: { seo_title: 'BER Assessors in Dublin | The Berman', seo_description: 'Find certified BER assessors in Dublin. Compare quotes and book online instantly.', meta_keywords: 'BER assessor Dublin, energy cert Dublin', is_active: true },
                    spain: { seo_title: 'Técnicos Certificados en Madrid | Certificado Energético', seo_description: 'Encuentra técnicos certificados en Madrid. Compara presupuestos y reserva online.', meta_keywords: 'certificado energético Madrid, técnico Madrid', is_active: true },
                    england: { seo_title: 'EPC Assessors in London | EPC Cert', seo_description: 'Find certified EPC assessors in London. Compare quotes and book online instantly.', meta_keywords: 'EPC assessor London, energy cert London', is_active: true },
                    france: { seo_title: 'Diagnostiqueurs DPE à Paris | DPE France', seo_description: 'Trouvez des diagnostiqueurs DPE certifiés à Paris. Comparez les devis et réservez en ligne.', meta_keywords: 'DPE Paris, diagnostiqueur Paris', is_active: true },
                    portugal: { seo_title: 'Peritos Certificados em Lisboa | Certificado Energético', seo_description: 'Encontre peritos certificados em Lisboa. Compare orçamentos e reserve online.', meta_keywords: 'certificado energético Lisboa, perito Lisboa', is_active: true },
                },
            },
        ],
    },
    {
        id: 'faq',
        label: 'FAQ',
        labels: { spain: 'FAQ', france: 'FAQ', portugal: 'FAQ' },
        path: '/faq',
        sections: [
            {
                id: 'hero',
                label: 'Hero Section',
                labels: { spain: 'Sección Hero', france: 'Section Hero', portugal: 'Secção Hero' },
                description: 'FAQ page header',
                descriptions: { spain: 'Encabezado de la página FAQ', france: 'En-tête de la page FAQ', portugal: 'Cabeçalho da página FAQ' },
                icon: '❓',
                fields: [
                    { key: 'badge', label: 'Badge Text', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'subtitle', label: 'Subtitle', type: 'textarea', group: 'Content' },
                    { key: 'hero_image', label: 'Hero Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: { badge: 'Knowledge Base', heading: 'Frequently Asked Questions', subtitle: 'Find answers to the most common questions about BER assessments, energy ratings, and our services.', hero_image: '' },
                    spain: { badge: 'Base de Conocimiento', heading: 'Preguntas Frecuentes', subtitle: 'Encuentra respuestas a las preguntas más comunes sobre certificaciones energéticas, calificaciones y nuestros servicios.', hero_image: '' },
                    england: { badge: 'Knowledge Base', heading: 'Frequently Asked Questions', subtitle: 'Find answers to the most common questions about EPC assessments, energy ratings, and our services.', hero_image: '' },
                    france: { badge: 'Base de Connaissances', heading: 'Questions Fréquentes', subtitle: 'Trouvez les réponses aux questions les plus courantes sur les diagnostics DPE, les performances énergétiques et nos services.', hero_image: '' },
                    portugal: { badge: 'Base de Conhecimento', heading: 'Perguntas Frequentes', subtitle: 'Encontre respostas às perguntas mais comuns sobre certificações energéticas, avaliações e os nossos serviços.', hero_image: '' },
                },
            },
            {
                id: 'cta',
                label: 'Bottom CTA',
                labels: { spain: 'CTA Inferior', france: 'CTA Bas de Page', portugal: 'CTA Inferior' },
                description: 'Call to action at bottom of FAQ page',
                descriptions: { spain: 'Llamada a la acción al final de la página FAQ', france: 'Appel à l\'action en bas de la page FAQ', portugal: 'Chamada à ação no final da página FAQ' },
                icon: '📣',
                fields: [
                    { key: 'heading', label: 'CTA Heading', type: 'text', group: 'Content' },
                    { key: 'description', label: 'CTA Description', type: 'textarea', group: 'Content' },
                    { key: 'button_text', label: 'Button Text', type: 'text', group: 'Content' },
                    { key: 'button_url', label: 'Button URL', type: 'url', group: 'Content' },
                    { key: 'cta_image', label: 'CTA Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: { heading: "Ireland's Leading BER Consultants", description: 'Trusted by homeowners across the country.', button_text: 'Contact Us', button_url: '/contact-us', cta_image: '' },
                    spain: { heading: '¿Todavía tienes preguntas?', description: 'Nuestro equipo está aquí para ayudarte. Ponte en contacto para asistencia personalizada.', button_text: 'Contáctanos', button_url: '/contact-us', cta_image: '' },
                    england: { heading: 'Still have questions?', description: 'Our team is here to help. Get in touch for personalised assistance.', button_text: 'Contact Us', button_url: '/contact-us', cta_image: '' },
                    france: { heading: 'Vous avez encore des questions ?', description: 'Notre équipe est là pour vous aider. Contactez-nous pour une assistance personnalisée.', button_text: 'Contactez-nous', button_url: '/contact-us', cta_image: '' },
                    portugal: { heading: 'Ainda tem perguntas?', description: 'A nossa equipa está aqui para ajudar. Entre em contacto para assistência personalizada.', button_text: 'Contacte-nos', button_url: '/contact-us', cta_image: '' },
                },
            },
        ],
    },
    {
        id: 'catalogue',
        label: 'Catalogue',
        labels: { spain: 'Catálogo', france: 'Catalogue', portugal: 'Catálogo' },
        path: '/catalogue',
        sections: [
            {
                id: 'hero',
                label: 'Hero Section',
                labels: { spain: 'Sección Hero', france: 'Section Hero', portugal: 'Secção Hero' },
                description: 'Catalogue page header',
                descriptions: { spain: 'Encabezado de la página de catálogo', france: 'En-tête de la page catalogue', portugal: 'Cabeçalho da página de catálogo' },
                icon: '📦',
                fields: [
                    { key: 'badge', label: 'Badge Text', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'subtitle', label: 'Subtitle', type: 'textarea', group: 'Content' },
                    { key: 'hero_image', label: 'Hero Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: { badge: 'Our Network', heading: 'Home Energy Upgrade Catalogue', subtitle: 'Browse our curated network of certified home energy professionals. Find solar installers, insulation experts, heat pump specialists and more.', hero_image: '' },
                    spain: { badge: 'Nuestra Red', heading: 'Catálogo de Mejoras Energéticas', subtitle: 'Explora nuestra red seleccionada de profesionales certificados en eficiencia energética. Encuentra instaladores de solar, expertos en aislamiento, especialistas en bombas de calor y más.', hero_image: '' },
                    england: { badge: 'Our Network', heading: 'Home Energy Upgrade Catalogue', subtitle: 'Browse our curated network of certified home energy professionals. Find solar installers, insulation experts, heat pump specialists and more.', hero_image: '' },
                    france: { badge: 'Notre Réseau', heading: 'Catalogue de Rénovation Énergétique', subtitle: 'Parcourez notre réseau de professionnels certifiés en énergie. Trouvez des installateurs solaires, experts en isolation, spécialistes en pompes à chaleur et plus.', hero_image: '' },
                    portugal: { badge: 'A Nossa Rede', heading: 'Catálogo de Melhorias Energéticas', subtitle: 'Explore a nossa rede de profissionais certificados em eficiência energética. Encontre instaladores de solar, especialistas em isolamento, técnicos de bombas de calor e mais.', hero_image: '' },
                },
            },
            {
                id: 'features',
                label: 'Features',
                labels: { spain: 'Características', france: 'Fonctionnalités', portugal: 'Funcionalidades' },
                description: 'Catalogue features section',
                descriptions: { spain: 'Sección de características del catálogo', france: 'Section fonctionnalités du catalogue', portugal: 'Secção de funcionalidades do catálogo' },
                icon: '✨',
                fields: [
                    { key: 'feature1_title', label: 'Feature 1 Title', type: 'text', group: 'Features' },
                    { key: 'feature1_desc', label: 'Feature 1 Description', type: 'textarea', group: 'Features' },
                    { key: 'feature1_image', label: 'Feature 1 Image', type: 'image', group: 'Features' },
                    { key: 'feature2_title', label: 'Feature 2 Title', type: 'text', group: 'Features' },
                    { key: 'feature2_desc', label: 'Feature 2 Description', type: 'textarea', group: 'Features' },
                    { key: 'feature2_image', label: 'Feature 2 Image', type: 'image', group: 'Features' },
                    { key: 'feature3_title', label: 'Feature 3 Title', type: 'text', group: 'Features' },
                    { key: 'feature3_desc', label: 'Feature 3 Description', type: 'textarea', group: 'Features' },
                    { key: 'feature3_image', label: 'Feature 3 Image', type: 'image', group: 'Features' },
                ],
                defaults: {
                    ireland: { feature1_title: 'Verified Professionals', feature1_desc: 'Every business is vetted and certified.', feature1_image: '', feature2_title: 'Compare Quotes', feature2_desc: 'Get competitive quotes from multiple providers.', feature2_image: '', feature3_title: 'Local Experts', feature3_desc: 'Find specialists in your area.', feature3_image: '' },
                    spain: { feature1_title: 'Profesionales Verificados', feature1_desc: 'Cada negocio está verificado y certificado.', feature1_image: '', feature2_title: 'Compara Presupuestos', feature2_desc: 'Obtén presupuestos competitivos de múltiples proveedores.', feature2_image: '', feature3_title: 'Expertos Locales', feature3_desc: 'Encuentra especialistas en tu zona.', feature3_image: '' },
                    england: { feature1_title: 'Verified Professionals', feature1_desc: 'Every business is vetted and certified.', feature1_image: '', feature2_title: 'Compare Quotes', feature2_desc: 'Get competitive quotes from multiple providers.', feature2_image: '', feature3_title: 'Local Experts', feature3_desc: 'Find specialists in your area.', feature3_image: '' },
                    france: { feature1_title: 'Professionnels Vérifiés', feature1_desc: 'Chaque entreprise est vérifiée et certifiée.', feature1_image: '', feature2_title: 'Comparez les Devis', feature2_desc: 'Obtenez des devis compétitifs de plusieurs fournisseurs.', feature2_image: '', feature3_title: 'Experts Locaux', feature3_desc: 'Trouvez des spécialistes dans votre région.', feature3_image: '' },
                    portugal: { feature1_title: 'Profissionais Verificados', feature1_desc: 'Cada negócio é verificado e certificado.', feature1_image: '', feature2_title: 'Compare Orçamentos', feature2_desc: 'Obtenha orçamentos competitivos de vários fornecedores.', feature2_image: '', feature3_title: 'Especialistas Locais', feature3_desc: 'Encontre especialistas na sua área.', feature3_image: '' },
                },
            },
        ],
    },
    {
        id: 'news',
        label: 'News',
        labels: { spain: 'Noticias', france: 'Actualités', portugal: 'Notícias' },
        path: '/news',
        sections: [
            {
                id: 'hero',
                label: 'Hero Section',
                labels: { spain: 'Sección Hero', france: 'Section Hero', portugal: 'Secção Hero' },
                description: 'News page header',
                descriptions: { spain: 'Encabezado de la página de noticias', france: 'En-tête de la page actualités', portugal: 'Cabeçalho da página de notícias' },
                icon: '📰',
                fields: [
                    { key: 'badge', label: 'Badge Text', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'subtitle', label: 'Subtitle', type: 'textarea', group: 'Content' },
                    { key: 'hero_image', label: 'Hero Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: { badge: 'Latest Updates', heading: 'News & Updates', subtitle: 'Latest from The Berman on Energy, Grants and community', hero_image: '' },
                    spain: { badge: 'Últimas Noticias', heading: 'Nuestras Noticias', subtitle: 'Mantente informado con las últimas actualizaciones sobre regulaciones energéticas, subvenciones y tendencias del sector.', hero_image: '' },
                    england: { badge: 'Latest Updates', heading: 'Our News', subtitle: 'Stay informed with the latest updates on energy regulations, grants, and industry insights.', hero_image: '' },
                    france: { badge: 'Dernières Actualités', heading: 'Nos Actualités', subtitle: 'Restez informé des dernières mises à jour sur les réglementations énergétiques, les aides et les tendances du secteur.', hero_image: '' },
                    portugal: { badge: 'Últimas Atualizações', heading: 'As Nossas Notícias', subtitle: 'Mantenha-se informado com as últimas atualizações sobre regulamentos energéticos, subsídios e tendências do setor.', hero_image: '' },
                },
            },
            {
                id: 'featured',
                label: 'Featured Article',
                labels: { spain: 'Artículo Destacado', france: 'Article à la Une', portugal: 'Artigo em Destaque' },
                description: 'Featured news article section',
                descriptions: { spain: 'Sección de artículo destacado', france: 'Section article à la une', portugal: 'Secção de artigo em destaque' },
                icon: '⭐',
                fields: [
                    { key: 'tag', label: 'Tag', type: 'text', group: 'Content' },
                    { key: 'title', label: 'Title', type: 'text', group: 'Content' },
                    { key: 'excerpt', label: 'Excerpt', type: 'textarea', group: 'Content' },
                    { key: 'button_text', label: 'Button Text', type: 'text', group: 'Content' },
                    { key: 'featured_image', label: 'Featured Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: { tag: 'Featured', title: 'Understanding Energy Ratings', excerpt: 'Learn how energy ratings impact your property value and what you can do to improve.', button_text: 'Read More', featured_image: '' },
                    spain: { tag: 'Destacado', title: 'Entendiendo las Calificaciones Energéticas', excerpt: 'Aprende cómo las calificaciones energéticas impactan el valor de tu propiedad y qué puedes hacer para mejorar.', button_text: 'Leer Más', featured_image: '' },
                    england: { tag: 'Featured', title: 'Understanding Energy Ratings', excerpt: 'Learn how energy ratings impact your property value and what you can do to improve.', button_text: 'Read More', featured_image: '' },
                    france: { tag: 'À la Une', title: 'Comprendre les Diagnostics Énergétiques', excerpt: 'Apprenez comment les diagnostics énergétiques impactent la valeur de votre bien et comment les améliorer.', button_text: 'Lire la Suite', featured_image: '' },
                    portugal: { tag: 'Destaque', title: 'Entender as Avaliações Energéticas', excerpt: 'Saiba como as avaliações energéticas impactam o valor da sua propriedade e o que pode fazer para melhorar.', button_text: 'Ler Mais', featured_image: '' },
                },
            },
        ],
    },
    {
        id: 'blog',
        label: 'Blog',
        labels: { spain: 'Blog', france: 'Blog', portugal: 'Blog' },
        path: '/blog',
        sections: [
            {
                id: 'hero',
                label: 'Hero Section',
                labels: { spain: 'Sección Hero', france: 'Section Hero', portugal: 'Secção Hero' },
                description: 'Blog page header',
                descriptions: { spain: 'Encabezado de la página de blog', france: 'En-tête de la page blog', portugal: 'Cabeçalho da página de blog' },
                icon: '✍️',
                fields: [
                    { key: 'badge', label: 'Badge Text', type: 'text', group: 'Content' },
                    { key: 'heading', label: 'Heading', type: 'text', group: 'Content' },
                    { key: 'subtitle', label: 'Subtitle', type: 'textarea', group: 'Content' },
                    { key: 'hero_image', label: 'Hero Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: { badge: 'Insights', heading: 'BER Blog Ireland', subtitle: 'Expert articles, guides, and tips on Building Energy Ratings, home efficiency, and certification in Ireland.', hero_image: '' },
                    spain: { badge: 'Consejos', heading: 'Blog Energético', subtitle: 'Artículos expertos, guías y consejos sobre eficiencia energética, mejoras del hogar y certificación.', hero_image: '' },
                    england: { badge: 'Insights', heading: 'Energy Blog', subtitle: 'Expert articles, guides, and tips on energy efficiency, home upgrades, and certification.', hero_image: '' },
                    france: { badge: 'Conseils', heading: 'Blog Énergie', subtitle: 'Articles experts, guides et astuces sur l\'efficacité énergétique, les rénovations et la certification.', hero_image: '' },
                    portugal: { badge: 'Dicas', heading: 'Blog de Energia', subtitle: 'Artigos de especialistas, guias e dicas sobre eficiência energética, melhorias em casa e certificação.', hero_image: '' },
                },
            },
            {
                id: 'featured',
                label: 'Featured Post',
                labels: { spain: 'Publicación Destacada', france: 'Article à la Une', portugal: 'Publicação em Destaque' },
                description: 'Featured blog post section',
                descriptions: { spain: 'Sección de publicación destacada del blog', france: 'Section article à la une du blog', portugal: 'Secção de publicação em destaque do blog' },
                icon: '⭐',
                fields: [
                    { key: 'tag', label: 'Tag', type: 'text', group: 'Content' },
                    { key: 'title', label: 'Title', type: 'text', group: 'Content' },
                    { key: 'excerpt', label: 'Excerpt', type: 'textarea', group: 'Content' },
                    { key: 'button_text', label: 'Button Text', type: 'text', group: 'Content' },
                    { key: 'featured_image', label: 'Featured Image', type: 'image', group: 'Media' },
                ],
                defaults: {
                    ireland: { tag: 'Featured', title: 'Top 10 Energy Saving Tips', excerpt: 'Discover practical ways to reduce your energy bills and improve your home\'s efficiency.', button_text: 'Read Article', featured_image: '' },
                    spain: { tag: 'Destacado', title: 'Top 10 Consejos para Ahorrar Energía', excerpt: 'Descubre formas prácticas de reducir tus facturas energéticas y mejorar la eficiencia de tu hogar.', button_text: 'Leer Artículo', featured_image: '' },
                    england: { tag: 'Featured', title: 'Top 10 Energy Saving Tips', excerpt: 'Discover practical ways to reduce your energy bills and improve your home\'s efficiency.', button_text: 'Read Article', featured_image: '' },
                    france: { tag: 'À la Une', title: 'Top 10 Conseils pour Économiser l\'Énergie', excerpt: 'Découvrez des moyens pratiques de réduire vos factures énergétiques et d\'améliorer l\'efficacité de votre logement.', button_text: 'Lire l\'Article', featured_image: '' },
                    portugal: { tag: 'Destaque', title: 'Top 10 Dicas para Poupar Energia', excerpt: 'Descubra formas práticas de reduzir as suas contas de energia e melhorar a eficiência da sua casa.', button_text: 'Ler Artigo', featured_image: '' },
                },
            },
        ],
    },
];

export function getDefaultsForTenant(pageId: string, sectionId: string, tenant: string): Record<string, any> {
    const page = CMS_PAGES.find(p => p.id === pageId);
    if (!page) return {};
    const section = page.sections.find(s => s.id === sectionId);
    if (!section) return {};
    const tenantKey = tenant as keyof typeof section.defaults;
    return section.defaults[tenantKey] || section.defaults.ireland || {};
}
